title: sigrid benezra
description: Personal website of Sigrid Benezra
baseurl: ""
url: https://sdbenezra.github.io/sdbenezra-portfolio/

remote_theme: cvless

# site settings
taglong: Software Engineer, Artist, Musician
tagshort: Software Engineer

# author settings
author:
  name: Sigrid Benezra
  email: sigrid@norwestagency.com
photo: assets/files/photo.jpg
address: Seattle, WA
phone: 206-499-8155

# social media links
social:
  facebook:
  github: sdbenezra
  instagram:
  linkedin: sdbenezra
  stackoverflow:
  x:

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md